### PR TITLE
Packing1D

### PR DESCRIPTION
**Pull request by CyberBLN**
I added the view part for the 1D cutlist, added a new "length" icon because "size" not really fit and fixed some minor issues in the 1D packaging engine like the saw kerf offset.

leftover tasks:
- in the french translation file you'll find translations starting with "TBT" (to be translated)
- in tools/icomoon/selection.json the new "length" icon is missing (no idea how to add correctly)
- in the cutlist_controller.rb the debugging code should be removed
- scrap bars usage is not implemented yet
- testing, testing, testing ;)

### CODE REVIEW

**Comment by bbeaulant** [comment]
Big job, thanks. I will take a look after Christmas :)

**Comment by bbeaulant** [comment]
Hi @CyberBLN,

Sorry for the long-time answer ...

Realy great job and I appreciate the way you did it according to my code style. But I've got some troubles with your changes and can't merge it.

1. In my opinion I18N in alphabetical order is not a good choice. Currently its ordered according to the UI presentation. And it may be easier to manage because it correspond to the visual way.
2. I split cutting-diagram 1D and 2D because I think that we can't render bars as panels. Else on big project it will be unreadable. In this way it mays be a wrong choice to write common templates. And thats way the feature in not available yet. Because the good way to render it is not find.

---

> in tools/icomoon/selection.json the new "length" icon is missing (no idea how to add correctly)

This is an autogenerated file from [icomoon.io/app](https://icomoon.io/app/#/select) application. 
And we can use this file to reimporte icon set to Icomoon to add a new one and re-generate the new fonts.

> scrap bars usage is not implemented yet

Yes due to its lake of time @mobilarte doesn't finalize this feature yet.

**Comment by bbeaulant** [comment]
Hi @CyberBLN,

Thanks a lot for your work, but as mentioned above, Packing1D strategy is quite different than 2D. Then, I'm sad to bypass your PR and put your work to trash.
But this morning I merge Packin1D branch into master and if you want you can test it our solution. And if you find bugs do not hesitate to make a PR. I will be happy to see you in contributors.
Have a nice day !

**Comment by iveney** [comment]
@bbeaulant how does Packing1D work? I tried the latest master and did not see a cutting diagram for lumber material.

**Comment by bbeaulant** [comment]
@iveney last release is not yet published. To test packing 1D, you need to download the last DEV build : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz

**Pull request closed without merging**
