### PR TITLE
~ Added 1D/2D bin packing libraries, console output

### PR DESCRIPTION
**Pull request by mobilarte**
First commit with:

1D: only outputs into ruby console with fixed values from cutlist_controller.rb
2D: creates directory /tmp/lairdubois_test and outputs cutlist diagrams in html format as well as ruby console output.

### CODE REVIEW

**Comment by bbeaulant** [comment]
Nice job ! Maybe it would be preferable to put the packer logic in a new controller of a new tab, no ?

**Comment by mobilarte** [comment]
Thanks!

The button is at the right place, but maybe the result should open in a new tab, then it would make sense to put it into a new controller. Feel free to rearrange the code as you see fit.

**Comment by bbeaulant** [comment]
Yes. I propose to named this new tab "cutdiagram". What do you think about this ?

**Comment by mobilarte** [comment]
Fine with me!

**Comment by bbeaulant** [comment]
Ok ;)

**Pull request merged**
